// Brand name → category key mapping for DACH (DE/AT/CH) region
// Manually curated from Open Food Facts data and common DACH supermarket brands
// Keys are lowercase brand names
export const BRAND_CATEGORIES: Record<string, string> = {

	// ── Snacks & Süßes ──────────────────────────────────────────────────────
	'haribo': 'snacks',
	'trolli': 'snacks',
	'katjes': 'snacks',
	'nimm2': 'snacks',
	'nimm 2': 'snacks',
	'lutti': 'snacks',
	'milka': 'snacks',
	'ritter sport': 'snacks',
	'lindt': 'snacks',
	'toblerone': 'snacks',
	'merci': 'snacks',
	'ferrero': 'snacks',
	'nutella': 'snacks',
	'kinder': 'snacks',
	'raffaello': 'snacks',
	'rocher': 'snacks',
	'ferrero rocher': 'snacks',
	'bounty': 'snacks',
	'mars': 'snacks',
	'snickers': 'snacks',
	'twix': 'snacks',
	'kitkat': 'snacks',
	'kit kat': 'snacks',
	'oreo': 'snacks',
	'leibniz': 'snacks',
	'bahlsen': 'snacks',
	'manner': 'snacks',
	'zotter': 'snacks',
	'toffifee': 'snacks',
	"werther's": 'snacks',
	'werther': 'snacks',
	'storck': 'snacks',
	'knoppers': 'snacks',
	'hanuta': 'snacks',
	'prinzenrolle': 'snacks',
	'prinzen rolle': 'snacks',
	'pringles': 'snacks',
	'lays': 'snacks',
	"lay's": 'snacks',
	'funny-frisch': 'snacks',
	'funny frisch': 'snacks',
	'chio': 'snacks',
	'lorenz': 'snacks',
	'saltletts': 'snacks',
	'intersnack': 'snacks',
	'mentos': 'snacks',
	'tic tac': 'snacks',
	'wrigley': 'snacks',
	"wrigley's": 'snacks',
	'jacobs krönung': 'snacks',
	'duplo': 'snacks',
	'celebration': 'snacks',
	'm&m': 'snacks',
	'skittles': 'snacks',
	'starburst': 'snacks',
	'maltesers': 'snacks',
	'lion': 'snacks',
	'after eight': 'snacks',
	'rolo': 'snacks',
	'smarties': 'snacks',
	'dr. oetker schokolade': 'snacks',
	'rausch': 'snacks',
	'vivani': 'snacks',
	'sarotti': 'snacks',
	'sprüngli': 'snacks',
	'cailler': 'snacks',
	'camille bloch': 'snacks',
	'frey': 'snacks',

	// ── Milch & Käse ────────────────────────────────────────────────────────
	'müller': 'milch',
	'ehrmann': 'milch',
	'danone': 'milch',
	'activia': 'milch',
	'actimel': 'milch',
	'alpro': 'milch',
	'oatly': 'milch',
	'berchtesgadener land': 'milch',
	'weihenstephan': 'milch',
	'bauer': 'milch',
	'hochland': 'milch',
	'leerdammer': 'milch',
	'président': 'milch',
	'president': 'milch',
	'arla': 'milch',
	'meggle': 'milch',
	'kerrygold': 'milch',
	'philadelphia': 'milch',
	'boursin': 'milch',
	'emmi': 'milch',
	'appenzeller': 'milch',
	'tilsiter': 'milch',
	'landliebe': 'milch',
	'nöm': 'milch',
	'tirol milch': 'milch',
	'schärdinger': 'milch',
	'bergader': 'milch',
	'allgäuer': 'milch',
	'zott': 'milch',
	'frischli': 'milch',
	'milram': 'milch',
	'bresso': 'milch',
	'caprice des dieux': 'milch',
	'castello': 'milch',
	'dairygold': 'milch',
	'exquisa': 'milch',
	'freihofer': 'milch',
	'gran moravia': 'milch',
	'gruyère': 'milch',
	'jarlsberg': 'milch',
	'küstengold': 'milch',
	'la vache qui rit': 'milch',
	'laughing cow': 'milch',
	'muh': 'milch',
	'paulaner': 'milch',
	'tegernseer': 'milch',
	'söbbeke': 'milch',
	'andechser': 'milch',
	'demeter': 'milch',
	'alnatura': 'milch',
	'bio-molkerei': 'milch',

	// ── Backwaren & Frühstück ────────────────────────────────────────────────
	'kellogg': 'backwaren',
	"kellogg's": 'backwaren',
	'nestlé cereals': 'backwaren',
	'dr. oetker': 'backwaren',
	'dr oetker': 'backwaren',
	'wasa': 'backwaren',
	'ryvita': 'backwaren',
	'finn crisp': 'backwaren',
	'mestemacher': 'backwaren',
	'golden toast': 'backwaren',
	'harry': 'backwaren',
	'quaker': 'backwaren',
	'weetabix': 'backwaren',
	'jordans': 'backwaren',
	'müsli': 'backwaren',
	'seitenbacher': 'backwaren',
	'bauckhof': 'backwaren',
	'schär': 'backwaren',
	'diamant': 'backwaren',
	'mondamin': 'backwaren',
	'gustin': 'backwaren',
	'uncle tobys': 'backwaren',
	'back-family': 'backwaren',
	'nature valley': 'backwaren',
	'corny': 'backwaren',
	'griesson': 'backwaren',
	'de beukelaer': 'backwaren',
	'mcvitie': 'backwaren',
	"mcvitie's": 'backwaren',
	'digestive': 'backwaren',
	'knäckebrot': 'backwaren',
	'pumpernickel': 'backwaren',
	'mit liebe': 'backwaren',
	'coppenrath': 'backwaren',
	'coppenrath & wiese': 'backwaren',
	'lantmännen': 'backwaren',
	'fazer': 'backwaren',

	// ── Fleisch & Fisch ──────────────────────────────────────────────────────
	'rügenwalder': 'fleisch',
	'rügenwalder mühle': 'fleisch',
	'wiesenhof': 'fleisch',
	'herta': 'fleisch',
	'reinert': 'fleisch',
	'stockmeyer': 'fleisch',
	'böklunder': 'fleisch',
	'meica': 'fleisch',
	'dulano': 'fleisch',
	'gutfried': 'fleisch',
	'zimbo': 'fleisch',
	'aoste': 'fleisch',
	'jack links': 'fleisch',
	"jack link's": 'fleisch',
	'followfish': 'fleisch',
	'iglo': 'fleisch',
	'frosta': 'fleisch',
	'msc': 'fleisch',
	'appel': 'fleisch',
	'nixe': 'fleisch',
	'armada': 'fleisch',
	'lisner': 'fleisch',
	'hawesta': 'fleisch',
	'rio mare': 'fleisch',
	'callipo': 'fleisch',
	'saupiquet': 'fleisch',
	'rügen fisch': 'fleisch',
	'rügen-fisch': 'fleisch',
	'salzbrenner': 'fleisch',
	'alpenschinken': 'fleisch',
	'berger schinken': 'fleisch',
	'stastnik': 'fleisch',
	'radatz': 'fleisch',
	'tulip': 'fleisch',
	'john west': 'fleisch',

	// ── Getränke ─────────────────────────────────────────────────────────────
	'coca-cola': 'getraenke',
	'coca cola': 'getraenke',
	'coke': 'getraenke',
	'pepsi': 'getraenke',
	'fanta': 'getraenke',
	'sprite': 'getraenke',
	'mezzo mix': 'getraenke',
	'fritz-kola': 'getraenke',
	'fritz kola': 'getraenke',
	'fritz': 'getraenke',
	'bionade': 'getraenke',
	'afri-cola': 'getraenke',
	'afri cola': 'getraenke',
	'almdudler': 'getraenke',
	'volvic': 'getraenke',
	'evian': 'getraenke',
	'gerolsteiner': 'getraenke',
	'apollinaris': 'getraenke',
	'römerquelle': 'getraenke',
	'vilsa': 'getraenke',
	'adelholzener': 'getraenke',
	'bad homburger': 'getraenke',
	'staatl. fachingen': 'getraenke',
	'hohes c': 'getraenke',
	'granini': 'getraenke',
	'tropicana': 'getraenke',
	'rauch': 'getraenke',
	'pfanner': 'getraenke',
	'innocent': 'getraenke',
	'true fruits': 'getraenke',
	'red bull': 'getraenke',
	'monster': 'getraenke',
	'rockstar': 'getraenke',
	'burn': 'getraenke',
	'paulaner': 'getraenke',
	'weihenstephan bier': 'getraenke',
	'erdinger': 'getraenke',
	'hofbräu': 'getraenke',
	'augustiner': 'getraenke',
	'warsteiner': 'getraenke',
	'bitburger': 'getraenke',
	'krombacher': 'getraenke',
	"beck's": 'getraenke',
	'becks': 'getraenke',
	'veltins': 'getraenke',
	'radeberger': 'getraenke',
	'jever': 'getraenke',
	'corona': 'getraenke',
	'heineken': 'getraenke',
	'carlsberg': 'getraenke',
	'gösser': 'getraenke',
	'ottakringer': 'getraenke',
	'schwechater': 'getraenke',
	'zipfer': 'getraenke',
	'feldschlösschen': 'getraenke',
	'cardinal': 'getraenke',
	'nescafé': 'getraenke',
	'nescafe': 'getraenke',
	'jacobs': 'getraenke',
	'melitta': 'getraenke',
	'dallmayr': 'getraenke',
	'tchibo': 'getraenke',
	'eduscho': 'getraenke',
	'lavazza': 'getraenke',
	'illy': 'getraenke',
	'senseo': 'getraenke',
	'teekanne': 'getraenke',
	'meßmer': 'getraenke',
	'messmer': 'getraenke',
	'lipton': 'getraenke',
	'twinings': 'getraenke',
	'celestial seasonings': 'getraenke',
	'capri-sonne': 'getraenke',
	'capri sonne': 'getraenke',
	'capri sun': 'getraenke',
	'rivella': 'getraenke',
	'ramseier': 'getraenke',
	'feldschlösschen': 'getraenke',

	// ── Tiefkühl ─────────────────────────────────────────────────────────────
	'iglo tiefkühl': 'tiefkuehl',
	'frosta tiefkühl': 'tiefkuehl',
	'dr. oetker pizza': 'tiefkuehl',
	'wagner': 'tiefkuehl',
	'ristorante': 'tiefkuehl',
	'gustavo gusto': 'tiefkuehl',
	'bofrost': 'tiefkuehl',
	'apetito': 'tiefkuehl',
	'findus': 'tiefkuehl',
	'mccain': 'tiefkuehl',
	'mc cain': 'tiefkuehl',
	'langnese': 'tiefkuehl',
	'häagen-dazs': 'tiefkuehl',
	'haagen-dazs': 'tiefkuehl',
	'haagen dazs': 'tiefkuehl',
	'ben & jerry': 'tiefkuehl',
	"ben & jerry's": 'tiefkuehl',
	'magnum': 'tiefkuehl',
	'cornetto': 'tiefkuehl',
	'viennetta': 'tiefkuehl',
	'cremissimo': 'tiefkuehl',
	'schöller': 'tiefkuehl',
	'mövenpick': 'tiefkuehl',
	'movenpick': 'tiefkuehl',
	'mövenpick eis': 'tiefkuehl',
	'carte d\'or': 'tiefkuehl',
	'carte dor': 'tiefkuehl',
	'walls': 'tiefkuehl',
	'eismann': 'tiefkuehl',
	'chicago town': 'tiefkuehl',
	'american style': 'tiefkuehl',
	'block house': 'tiefkuehl',

	// ── Haushalt & Pflege ────────────────────────────────────────────────────
	'persil': 'haushalt',
	'ariel': 'haushalt',
	'lenor': 'haushalt',
	'perwoll': 'haushalt',
	'spee': 'haushalt',
	'weißer riese': 'haushalt',
	'frosch': 'haushalt',
	'fit': 'haushalt',
	'fairy': 'haushalt',
	'pril': 'haushalt',
	'palmolive': 'haushalt',
	'meister proper': 'haushalt',
	'mr. proper': 'haushalt',
	'mr proper': 'haushalt',
	'ajax': 'haushalt',
	'domestos': 'haushalt',
	'sagrotan': 'haushalt',
	'dettol': 'haushalt',
	'cillit bang': 'haushalt',
	'viss': 'haushalt',
	'bref': 'haushalt',
	'wc ente': 'haushalt',
	'somat': 'haushalt',
	'finish': 'haushalt',
	'nivea': 'haushalt',
	'dove': 'haushalt',
	'fa': 'haushalt',
	'rexona': 'haushalt',
	'axe': 'haushalt',
	'head & shoulders': 'haushalt',
	'pantene': 'haushalt',
	'schwarzkopf': 'haushalt',
	'garnier': 'haushalt',
	'herbal essences': 'haushalt',
	'schauma': 'haushalt',
	'balea': 'haushalt',
	'alverde': 'haushalt',
	'alterra': 'haushalt',
	'elmex': 'haushalt',
	'signal': 'haushalt',
	'oral-b': 'haushalt',
	'oral b': 'haushalt',
	'colgate': 'haushalt',
	'sensodyne': 'haushalt',
	'odol': 'haushalt',
	'wilkinson': 'haushalt',
	'gillette': 'haushalt',
	'venus': 'haushalt',
	'always': 'haushalt',
	'tampax': 'haushalt',
	'o.b.': 'haushalt',
	'ob': 'haushalt',
	'carefree': 'haushalt',
	'libresse': 'haushalt',
	'tempo': 'haushalt',
	'zewa': 'haushalt',
	'hakle': 'haushalt',
	'kleenex': 'haushalt',
	'swirl': 'haushalt',
	'toppits': 'haushalt',
	'vileda': 'haushalt',
	'leifheit': 'haushalt',
	'erdal': 'haushalt',
	'kiwi': 'haushalt',
	'frosch': 'haushalt',
	'dr. beckmann': 'haushalt',
	'dr beckmann': 'haushalt',
	'vanish': 'haushalt',
	'febreze': 'haushalt',
	'ambi pur': 'haushalt',
	'airwick': 'haushalt',
	'glade': 'haushalt',
	'l\'oreal': 'haushalt',
	'loreal': 'haushalt',
	"l'oréal": 'haushalt',
	'maybelline': 'haushalt',
	'neutrogena': 'haushalt',
	'eucerin': 'haushalt',
	'beiersdorf': 'haushalt',
	'la roche-posay': 'haushalt',
	'vichy': 'haushalt',
	'sebamed': 'haushalt',
	'bebe': 'haushalt',
	'penaten': 'haushalt',
	'pampers': 'haushalt',
	'huggies': 'haushalt',
	'lillydoo': 'haushalt',
	'dm': 'haushalt',
	'rossmann': 'haushalt',

	// ── Nudeln & Reis ────────────────────────────────────────────────────────
	'barilla': 'nudeln',
	'de cecco': 'nudeln',
	'birkel': 'nudeln',
	'buitoni': 'nudeln',
	'riesa': 'nudeln',
	'combino': 'nudeln',
	'steinhaus': 'nudeln',
	'uncle bens': 'nudeln',
	"uncle ben's": 'nudeln',
	'ben\'s original': 'nudeln',
	'bens original': 'nudeln',
	'oryza': 'nudeln',
	'tilda': 'nudeln',
	'veetee': 'nudeln',
	'rapunzel nudeln': 'nudeln',

	// ── Konserven & Saucen ───────────────────────────────────────────────────
	'heinz': 'konserven',
	'knorr': 'konserven',
	'maggi': 'konserven',
	'thomy': 'konserven',
	'develey': 'konserven',
	'kühne': 'konserven',
	'kuhne': 'konserven',
	'hengstenberg': 'konserven',
	'felix': 'konserven',
	'bertolli': 'gewuerze',
	'mazola': 'gewuerze',
	'rapso': 'gewuerze',
	'lukull': 'konserven',
	'homann': 'konserven',
	'kraft': 'konserven',
	'miracel whip': 'konserven',
	'miracle whip': 'konserven',
	'hellmann\'s': 'konserven',
	'hellmanns': 'konserven',
	'maille': 'konserven',
	'händlmaier': 'konserven',
	'händlmaier\'s': 'konserven',
	'remia': 'konserven',
	'kania': 'konserven',
	'baltico': 'konserven',
	'ibis': 'konserven',
	'rapunzel': 'konserven',
	'alnatura öl': 'konserven',
	'de rica': 'konserven',
	'cirio': 'konserven',
	'mutti': 'konserven',
	'curtice brothers': 'konserven',

	// ── Bio-Marken (kategorieübergreifend je nach Produkt) ───────────────────
	'alnatura': 'obst',        // primär Obst/Gemüse & Grundnahrung → default obst
	'dennree': 'obst',
	'dm bio': 'obst',
	'bio wertkost': 'obst',
	'bioland': 'obst',
	'demeter': 'obst',
	'naturkind': 'obst',
	'füllhorn': 'obst',

	// ── Supermarkt-Eigenmarken: Rewe ─────────────────────────────────────────
	'ja!': 'obst',
	'rewe bio': 'obst',
	'rewe beste wahl': 'obst',
	'rewe feine welt': 'konserven',

	// ── Supermarkt-Eigenmarken: Edeka ────────────────────────────────────────
	'gut & günstig': 'obst',
	'gut und günstig': 'obst',
	'edeka bio': 'obst',
	'edeka selection': 'konserven',

	// ── Supermarkt-Eigenmarken: Lidl ─────────────────────────────────────────
	'milbona': 'milch',
	'freshona': 'obst',
	'crownfield': 'backwaren',
	'vitafit': 'getraenke',
	'saskia': 'getraenke',
	'solevita': 'getraenke',
	'linessa': 'milch',
	'picard': 'tiefkuehl',
	'bio organic': 'obst',

	// ── Supermarkt-Eigenmarken: Aldi ─────────────────────────────────────────
	'milsani': 'milch',
	'harvest basket': 'backwaren',
	'simply nature': 'obst',
	'back country': 'backwaren',
	'birkenhof': 'fleisch',
	'grandessa': 'konserven',
	'goldähren': 'backwaren',
	'dessert': 'snacks',

	// ── Supermarkt-Eigenmarken: Kaufland ─────────────────────────────────────
	'k-classic': 'obst',
	'k-bio': 'obst',
	'k-favourites': 'snacks',
	'k-take it veggie': 'fleisch',

	// ── Supermarkt-Eigenmarken: Penny / Netto ────────────────────────────────
	'penny': 'obst',
	'naturgut': 'obst',
	'san fabio': 'nudeln',

	// ── Gewürze & Zutaten ────────────────────────────────────────────────────
	'fuchs': 'gewuerze',
	'kotányi': 'gewuerze',
	'kotanyi': 'gewuerze',
	'mccormick': 'gewuerze',
	'ankerkraut': 'gewuerze',
	'just spices': 'gewuerze',
	'ostmann': 'gewuerze',
	'verstegen': 'gewuerze',
	'herbaria': 'gewuerze',
	'sonnentor': 'gewuerze',
	'alnatura gewürze': 'gewuerze',
	'lebensbaum': 'gewuerze',
	'bio planète': 'gewuerze',
	'bio planete': 'gewuerze',
	'wiberg': 'gewuerze',
	'kikkoman': 'gewuerze',
	'knorr würzmittel': 'gewuerze',
	'maggi würze': 'gewuerze',
	'felix essig': 'gewuerze',
	'kühne essig': 'gewuerze',
	'hela': 'gewuerze',
	'union': 'gewuerze',
	'schwartau': 'konserven',
	'zentis': 'konserven',
	'bonne maman': 'konserven',
	'darbo': 'konserven',
	'staud\'s': 'konserven',
	'stauds': 'konserven',
};
